//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingListApp.I18N.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingListApp.I18N.Resources.Views.Home.IndexCommon", typeof(IndexCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup via e-mail.
        /// </summary>
        public static string BackupEmail {
            get {
                return ResourceManager.GetString("BackupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup done on.
        /// </summary>
        public static string BackupMessage {
            get {
                return ResourceManager.GetString("BackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string BrowseItemFile {
            get {
                return ResourceManager.GetString("BrowseItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Lists.
        /// </summary>
        public static string BrowseShoppingListFile {
            get {
                return ResourceManager.GetString("BrowseShoppingListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing technical problems. Please try later..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup could not be delivered to your e-mail address. Please check that your inbox is not full and that your provider does not experience problems..
        /// </summary>
        public static string DeliveryFailed {
            get {
                return ResourceManager.GetString("DeliveryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Shopping List.
        /// </summary>
        public static string DueShoppingList {
            get {
                return ResourceManager.GetString("DueShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup aborted: no files to backup.
        /// </summary>
        public static string NoFilesToBackup {
            get {
                return ResourceManager.GetString("NoFilesToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files to restore..
        /// </summary>
        public static string NoFilesToRestore {
            get {
                return ResourceManager.GetString("NoFilesToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        public static string RestoreBackup {
            get {
                return ResourceManager.GetString("RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restored on.
        /// </summary>
        public static string RestoreBackupMessage {
            get {
                return ResourceManager.GetString("RestoreBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Items XSD.
        /// </summary>
        public static string RestoreItemsFailure {
            get {
                return ResourceManager.GetString("RestoreItemsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Shopping Lists XSD.
        /// </summary>
        public static string RestoreShoppingListsFailure {
            get {
                return ResourceManager.GetString("RestoreShoppingListsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Lists.
        /// </summary>
        public static string ShoppingLists {
            get {
                return ResourceManager.GetString("ShoppingLists", resourceCulture);
            }
        }
    }
}
